name: ideative
favicon: null
layout_spectrum: 0.23078
typography_spectrum: 0.80903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#000000'
    - '#d4bba5'
    - '#aa7b54'
    - '#79491e'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
